/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package part2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFound(){
        //girilen eleman array de mevcut. bu fonksiyondan true dönmeli
        ArrayList<Integer> array=new ArrayList<>(Arrays.asList(1,2,3,4));
        assertTrue(App.search(array, 4));
    }

    @Test
    public void testNotFound(){
        //girilen eleman array de mevcut değil. bu fonksiyondan false dönmeli
        ArrayList<Integer> array=new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.search(array, 5));
    }

    @Test
    public void testEmptFound(){
        //array boş. bu fonksiyondan false dönmeli
        ArrayList<Integer> array=new ArrayList<>();
        assertFalse(App.search(array, 1));
    }

    @Test
    public void testNull(){
        assertFalse(App.search(null, 1));
    }
}
